name: ci

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: Setup
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info

      - name: Coverage upload
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage
